### ISSUE TITLE
User Model: Add timestamp fields mailed_token_at, emailed_at

### ISSUE THREAD

**Issue by wbushey** [ballPointPenguin/adopt-a-tree#36]
The Adopt-a-Tree awareness program contacts users outside of the Adopt-a-Tree site in various ways, such as emailing them to ask for information or mailing them tokens. Adding fields to a user so that program managers could track this information on the site could help. These fields would not be visable on the public interface, only on the admin interface.

Both new fields should be timestamp fields.

**Comment by eebbesen** [comment]
PR accepted
