### ISSUE TITLE
Make page scrolling better - only the sidebar should be scrollable

### ISSUE THREAD

**Issue by wbushey** [ballPointPenguin/adopt-a-tree#42]
The sidebar has so much content that it requires a user to scroll to see all of the content. Currently, the map's height is set to match the height of the sidebar, meaning that the map now also requires to scroll to see the whole map. 

Ideally, the map's height should match the height of the viewport, while the sidebar should be scrollable.

**Comment by ballPointPenguin** [comment]
Going to take a stab at this.
