### ISSUE TITLE
Add "Share on Facebook/Twitter" functionality to end of adoption process

### ISSUE THREAD

**Issue by wbushey** [ballPointPenguin/adopt-a-tree#46]
The idea here is that once a user adopts a tree, they are presented with a button(s) to share their adoption to Facebook or Twitter. The buttons would open the standard sharing dialog for the social media site, pre-populated with something about adopting and naming a tree, and an URL.

**Comment by eebbesen** [comment]
https://developers.facebook.com/docs/plugins/share-button
https://dev.twitter.com/web/tweet-button

**Comment by wbushey** [comment]
Code has been deployed.
