### ISSUE TITLE
Code For America Tracker appears broken

### ISSUE THREAD

**Issue by eebbesen** [ballPointPenguin/adopt-a-tree#49]
http://stats.codeforamerica.org/ returns 503s for everyone, including this project's README.md.  Not sure how long this has been a thing.  If it is no longer supported it should be removed.

I'm having a hard time figuring out who to contact (via codeforamerica.org) to learn whether the stats service is being worked on or has been abandoned.  Suggestions?

**Comment by wbushey** [comment]
@eebbesen, where do you see the link to stats.codeforamerica.org? Is that in Adopt-A-Tree, or elsewhere?

@ondrae can probably tell us what's up with the Tracker

**Comment by wbushey** [comment]
Ahh, I see @eebbesen, it's linked to at the bottom of the readme (Adopt-A-Tree's and Adopt-A-Hydrant's).

**Comment by ondrae** [comment]
I think that stats thing was around back in 2013, but I haven't heard of it since then. Its nothing we support now. I'd remove the link to it.

**Comment by eebbesen** [comment]
PR accepted, this text is now gone
