### ISSUE TITLE
Should we add a code of conduct

### ISSUE THREAD

**Issue by eebbesen** [ballPointPenguin/adopt-a-tree#58]
I'm not sure if we have a linkable, blanket COC for CFA or our brigade.  If we do, where is it?  If we do not, should we add one to this project?

My initial thought on COCs was "We don't need them until we get jerks on the repo" but given issues in our country and our industry I now am convinced that an explicit statement of welcome along with an explicit statement of behavior we will not tolerate is a very good thing.

There are many who have thought about this in much more detail, but I propose copying from something like http://contributor-covenant.org/ which is the basis for [this recent rails commit] (https://github.com/rails/rails/pull/21292/files).

**Comment by ballPointPenguin** [comment]
I strongly support including a code of conduct in this project :rainbow:

**Comment by ballPointPenguin** [comment]
Another nice example is here:
http://emberjs.com/guidelines/

**Comment by wbushey** [comment]
Good catch @eebbesen. [OTC has a Code of Conduct](http://opentwincities.org/about/code-of-conduct/); it was put together mostly with events in mind, but I think it can be applied to open source project work.

**Comment by ballPointPenguin** [comment]
Simply linking to the OTC COC from the README here might be sufficient.
